apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: wujiabo1985/devops:latest
          imagePullPolicy: Never #just for minikube,do not use this in production!!!
          ports:
            - containerPort: 8001